# Generated by Django 5.0.7 on 2024-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBots',
            fields=[
                ('name_bot', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('type_bot', models.CharField(blank=True, max_length=100, null=True)),
                ('own_user', models.BigIntegerField(blank=True, null=True)),
                ('full_name_bot', models.CharField(blank=True, max_length=100, null=True)),
                ('http_api', models.CharField(blank=True, max_length=100, null=True)),
                ('date_pay', models.BigIntegerField(blank=True, null=True)),
                ('sum_pay', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('log', models.BigIntegerField(blank=True, null=True)),
                ('fbo', models.BigIntegerField(blank=True, null=True)),
                ('fbs', models.BigIntegerField(blank=True, null=True)),
                ('off', models.BigIntegerField(blank=True, null=True)),
                ('docum', models.BigIntegerField(blank=True, null=True)),
                ('pay_clients', models.BigIntegerField(blank=True, null=True)),
                ('pay_fbo', models.BigIntegerField(blank=True, null=True)),
                ('pay_fbs', models.BigIntegerField(blank=True, null=True)),
                ('pay_log', models.BigIntegerField(blank=True, null=True)),
                ('pic_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('support_pic_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('web_logo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'db_table': 'admin_bots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SokemUsers',
            fields=[
                ('id_user', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(blank=True, max_length=45, null=True)),
                ('act', models.CharField(blank=True, max_length=200, null=True)),
                ('json_user', models.CharField(blank=True, max_length=3000, null=True)),
                ('type_user', models.CharField(blank=True, max_length=300, null=True)),
                ('mes_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('ref_day', models.BigIntegerField(blank=True, null=True)),
                ('ref_user', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sokem_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupHelps',
            fields=[
                ('id_help', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_help', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sup_helps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupItems',
            fields=[
                ('id_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_item', models.CharField(blank=True, max_length=20, null=True)),
                ('arch', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sup_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupNews',
            fields=[
                ('id_new', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_new', models.CharField(blank=True, max_length=45, null=True)),
                ('name_user', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_user', models.CharField(blank=True, max_length=12, null=True)),
                ('link_tg', models.CharField(blank=True, max_length=100, null=True)),
                ('link_wa', models.CharField(blank=True, max_length=100, null=True)),
                ('date_create', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sup_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupReqs',
            fields=[
                ('id_req', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_req', models.CharField(blank=True, max_length=45, null=True)),
                ('type_req', models.CharField(blank=True, max_length=45, null=True)),
                ('name_user', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_user', models.CharField(blank=True, max_length=12, null=True)),
                ('where_user', models.CharField(blank=True, max_length=20, null=True)),
                ('when_user', models.CharField(blank=True, max_length=20, null=True)),
                ('name_bot', models.CharField(blank=True, max_length=45, null=True)),
                ('link_user', models.CharField(blank=True, max_length=100, null=True)),
                ('text_q', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_create', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sup_reqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupUsers',
            fields=[
                ('id_user', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(blank=True, max_length=10, null=True)),
                ('lk', models.CharField(blank=True, max_length=300, null=True)),
                ('act', models.CharField(blank=True, max_length=100, null=True)),
                ('lk_sup', models.CharField(blank=True, max_length=45, null=True)),
                ('full_name_user', models.CharField(blank=True, max_length=100, null=True)),
                ('link_tg', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_user', models.CharField(blank=True, max_length=12, null=True)),
                ('ref_name', models.CharField(blank=True, max_length=45, null=True)),
                ('obr', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('mes', models.CharField(blank=True, max_length=2002, null=True)),
                ('chan', models.CharField(blank=True, max_length=100, null=True)),
                ('json_user', models.CharField(blank=True, max_length=3000, null=True)),
                ('month_reg', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'sup_users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='AdminBots',
            name='web_logo',
            field=models.ImageField(upload_to='photos/', null=True, blank=True),
        ),
    ]
